---
title: "My Work Experience"
---

## Andrea M. Hall

Fort Collins, CO \|  (720) 940-0175 \| [andiehal\@colostate.edu](mailto:andiehal@colostate.edu)

### **Environmental Sustainability and Community Engagement Summary** 

Dedicated Ecosystem Science and Sustainability student with a strong work ethic, balancing academics with multiple jobs to gain hands-on experience. Over five years of diverse work experience in customer service, office administration, and lab research. Adept at multitasking, teamwork, and problem-solving, with a proven ability to adapt to different environments. Passionate about environmental sustainability, research, and community engagement. An experienced organizer and team leader who strives to connect with others. Skilled in programs such as R-Studio, Microsoft Excel, Microsoft Word, and ArcGIS.

### **Higher Education**

Bachelor of Science in Ecosystem Science and Sustainability	August 2022 - May 2026

Minor in Environmental and Natural Resource Economics	**GPA: 3.7**

   Colorado State University, Fort Collins, Colorado	

### **Relevant Environmental Research Experience** 

#### Research Mentee - CSU Skills for Undergraduate Participation in Ecological Research

Fort Collins, Colorado	August 2024 - May 2025

-   Expanding my knowledge of research skills while engaging in a mentorship with Dr. Anping Chen regarding the phenological cycles of a local bird species. 

-   Driving to refine and perfect my research report to publicly present at CSU’s annual CERC event.

#### Lab Intern - CSU OURA United in STEMM Lab Cohort 

Fort Collins, Colorado	January 2024 - May 2024

-   Engaged with faculty members to learn about standard laboratory practices.

-   Presented an independent project publicly at MURALS CSU and OURA Lab Showcase. 

#### Student Admin Assistant - CSU Office for the Vice President of Research 

Fort Collins, Colorado	September 2022 - May 2024

-   Provided a welcoming office environment and supported daily operations to enhance team workflow. 

-   Planning events and program development for the Vice President of Research and Associates.

### **Relevant Customer Service Experience** 

#### Swim Instructor - Aqua Tots: Swim School

Littleton, Colorado	January 2022 - August 2022

-   Educated groups young children how to practice water safety and perfect swimming strokes. 

-   Praised by parents and children for using creative and critical thinking skills to adapt to each kid’s needs.

#### Crew Member - Dunkin Donuts 

Fort Collins, Colorado	June 2024 - January 2025

-   Served customers while gaining experience in customer service to provide a quality experience! 

-   Developed leadership skills through management of fellow employees and established good relations.  

### **Relevant Course Experience**

Ecology - LIFE 320 	 Taken: July 2024 \| Grade: A

Introduction to Geospatial Science - NR 319 	Taken: Fall Semester 2024 \| Grade: B+

Environmental Economics - AREC 341 	Taken: Fall Semester 2024 \| Grade: A

Intermediate Economics - ECON 306	Taken: Fall Semester 2024 \| Grade: B+
